security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        profile_provider:
            entity:
                class: App\Entity\Profile
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(login-react|login-data)
            stateless: true
            security: false

        api:
            pattern: ^/(api|service-device|service-setting|service-settings-update|service-vibe-recommended|send-vibe|stop-vibe|stop-vibes-user|test-settings|service-planning)
            stateless: true
            provider: profile_provider
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login-react, roles: PUBLIC_ACCESS }
        - { path: ^/login-data, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/service-, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/send-vibe, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/stop-vibe, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/test-settings, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
