vich_uploader:
    db_driver: orm

    mappings:
        songs:
            uri_prefix: /upload/files//upload/files/music
            upload_destination: '%kernel.project_dir%/public/upload/files/music'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
