# version: '3.8'

services:
  apache_domotique:
    # nom du service
    build: apache # dossier contenant le Dockerfile
    container_name: apache_domotique # nom du container
    restart: always # redémarrage automatique
    ports:
      # ports exposés
      - "8082:80"
    volumes:
      # volumes montés
      - ./www:/var/www/html
      - ./apache/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    environment:
      # variables d'environnement
      - PHP_ERROR_REPORTING=E_ALL # afficher toutes les erreurs
      - PHP_DISPLAY_ERRORS=On # afficher les erreurs

  mariadb_domotique:
    # nom du service
    image: mariadb:latest # image à utiliser
    container_name: mariadb_domotique # nom du container
    restart: always # redémarrage automatique
    ports:
      # ports exposés
      - "3308:3306"
    environment:
      # variables d'environnement
      - TZ:Europe/Paris # fuseau horaire
      - MYSQL_ROOT_PASSWORD=superAdmin # mot de passe root
      - MYSQL_DATABASE=domotique # nom de la base de données
      - MYSQL_USER=admin # nom de l'utilisateur
      - MYSQL_PASSWORD=admin # mot de passe de l'utilisateur
    volumes:
      # volumes montés
      - mysql-domotique:/var/lib/mysql
      - ./db:/root # envoi le répertoire db dans le container
  
  mosquitto:
    # nom du service
    image: eclipse-mosquitto:latest # image à utiliser
    container_name: mqtt-broker # nom du container
    restart: always # redémarrage automatique
    ports:
      # ports exposés
      - "1883:1883" # port MQTT
      - "9001:9001" # port WebSocket
    volumes:
      # volumes montés
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  mysql-domotique:

networks:
  mqtt-net:
    driver: bridge
